image: alpine/edge
packages:
  - nodejs
  - rsync
  - tree-sitter-cli
secrets:
  - efb4ce30-ebb9-4966-b4c7-ade2fe600546
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - test: |
      cd tree-sitter-tcl
      make test
  - upload_to_github: |
      git clone \
        git@github.com:nawordar/tree-sitter-tcl.git \
        tree-sitter-tcl-generated
      cd tree-sitter-tcl
      scripts/upload_to_github.sh
